#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Render the validated Lean claim manifest into publication and Blueprint bindings.

Every output is derived deterministically from the same `generated/manifest.json`
and is stamped with its `content_hash`, so a caller can prove the renderer targets
consumed one manifest. Only `build_result: "checked"` claims are surfaced as
verified; a "failed" claim is emitted as an explicit not-verified marker, never
silently dropped.

Outputs:
- `generated/claim_manifest.tex` — shared LaTeX value bindings (all papers).
- `<blueprint>/src/generated/claim_bindings.tex` — LeanBlueprint declaration links.
- `<project>/src/generated/lean_status.tex` (per paper) — that paper's value
  bindings plus a `\\ppLeanStatusList` the manuscript renders. Publication prose
  consumes only `\\ppvalue{...}` / `\\ppLeanStatusList`, never a Lean identifier.

    uv run src/lean/tools/claim-manifest/render.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TOOL_DIR = Path(__file__).resolve().parent
LEAN_DIR = TOOL_DIR.parents[1]
REPO_ROOT = LEAN_DIR.parents[1]
PROJECTS_DIR = REPO_ROOT / "src" / "latex" / "projects"

HEADER = "AUTO-GENERATED by src/lean/tools/claim-manifest/render.py — do not edit by hand."


def render_latex(manifest: dict) -> str:
    lines = [
        f"% {HEADER}",
        f"% manifest_hash: {manifest['content_hash']}",
        "",
    ]
    lines.append(f"\\ppDeclareValue{{lean-manifest-hash}}{{{manifest['content_hash']}}}")
    for claim in manifest["claims"]:
        key = claim["claim_id"]
        verified = "checked" if claim["build_result"] == "checked" else "failed"
        lines.append(f"\\ppDeclareValue{{lean-verified-{key}}}{{{verified}}}")
        lines.append(f"\\ppDeclareValue{{lean-disclosure-{key}}}{{{claim['disclosure']}}}")
    lines.append("")
    return "\n".join(lines)


def render_paper_status(manifest: dict, paper: str) -> str:
    r"""Per-paper publication projection: value bindings + a status-list command.

    Consumed by the paper target via ``\input{generated/lean_status}``. The prose
    renders the machine-checked status through ``\ppLeanStatusList`` and
    ``\ppvalue{...}``, never a Lean identifier or source path.
    """
    claims = [c for c in manifest["claims"] if c["paper"] == paper]
    lines = [
        f"% {HEADER}",
        f"% manifest_hash: {manifest['content_hash']}",
        "",
    ]
    for claim in claims:
        key = claim["claim_id"]
        verified = "checked" if claim["build_result"] == "checked" else "failed"
        lines.append(f"\\ppDeclareValue{{lean-verified-{key}}}{{{verified}}}")
        lines.append(f"\\ppDeclareValue{{lean-disclosure-{key}}}{{{claim['disclosure']}}}")
    lines.append("")
    items = [
        f"    \\item \\Cref{{{c['claim_id']}}}: \\ppvalue{{lean-disclosure-{c['claim_id']}}}"
        for c in claims
        if c["build_result"] == "checked"
    ]
    if items:
        lines.append("\\newcommand{\\ppLeanStatusList}{%")
        lines.append("  \\begin{itemize}")
        lines.extend(items)
        lines.append("  \\end{itemize}%")
        lines.append("}")
    else:
        lines.append("\\newcommand{\\ppLeanStatusList}{}")
    lines.append("")
    return "\n".join(lines)


def render_blueprint(manifest: dict) -> str:
    r"""Project validated claim links into LeanBlueprint commands.

    Authored Blueprint prose names only a manuscript claim ID, through
    ``\ppClaimBinding{...}`` in the statement and ``\ppClaimProofBinding{...}``
    in the proof. The declaration link and verified markers live in this
    generated projection. LeanBlueprint colours a node from two independent
    slots — a statement ``\leanok`` and a proof ``\leanok`` — so a manifest
    entry that validated a complete sorry-free declaration must fill both or
    the graph would render 42 finished proofs as unproved. Failed entries
    deliberately expand only to ``\notready`` in both slots and therefore
    cannot claim verification.
    """
    lines = [
        f"% {HEADER}",
        f"% manifest_hash: {manifest['content_hash']}",
        "",
        "\\providecommand{\\ppClaimBinding}[1]{%",
        "  \\csname ppClaimBinding:#1\\endcsname%",
        "}",
        "\\providecommand{\\ppClaimProofBinding}[1]{%",
        "  \\csname ppClaimProofBinding:#1\\endcsname%",
        "}",
    ]
    for claim in manifest["claims"]:
        claim_id = claim["claim_id"]
        if claim["build_result"] == "checked":
            binding = f"\\lean{{{claim['declaration']}}}\\leanok"
            proof_binding = "\\leanok"
        else:
            binding = "\\notready"
            proof_binding = "\\notready"
        lines.append(
            f"\\expandafter\\def\\csname ppClaimBinding:{claim_id}\\endcsname{{{binding}}}"
        )
        lines.append(
            f"\\expandafter\\def\\csname ppClaimProofBinding:{claim_id}"
            f"\\endcsname{{{proof_binding}}}"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=TOOL_DIR / "generated" / "manifest.json")
    parser.add_argument("--out-dir", type=Path, default=TOOL_DIR / "generated")
    parser.add_argument(
        "--blueprint-out",
        type=Path,
        default=LEAN_DIR / "blueprint" / "src" / "generated" / "claim_bindings.tex",
    )
    parser.add_argument("--projects-dir", type=Path, default=PROJECTS_DIR)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    args.out_dir.mkdir(parents=True, exist_ok=True)

    latex_path = args.out_dir / "claim_manifest.tex"
    latex_path.write_text(render_latex(manifest))
    args.blueprint_out.parent.mkdir(parents=True, exist_ok=True)
    args.blueprint_out.write_text(render_blueprint(manifest))
    print(f"wrote {latex_path}")
    print(f"wrote {args.blueprint_out}")

    # Papers named by the manifest, UNION every paper that has a generated
    # directory at all. The union matters on withdrawal: iterating the manifest
    # alone would leave the last-claim-withdrawn paper holding a stale
    # projection that still asserts machine-checked backing for claims the
    # manifest no longer has. Rewriting it to the empty projection makes
    # withdrawal self-healing.
    #
    # Keyed on the *directory*, deliberately, not on an existing status file:
    # DVC deletes a stage's declared outs before running it, so by the time this
    # executes under `dvc repro` the very files that glob would look for are
    # already gone, and the union would silently collapse to the manifest.
    # Underscore-prefixed directories are scaffolding (`_template`), not papers;
    # writing a status projection into the template would ship a stale one into
    # every project created from it.
    claimed = {c["paper"] for c in manifest["claims"]}
    existing = {
        path.parents[1].name
        for path in args.projects_dir.glob("*/src/generated")
        if not path.parents[1].name.startswith("_")
    }
    for paper in sorted(claimed | existing):
        generated = args.projects_dir / paper / "src" / "generated"
        if not generated.exists():
            print(f"  skip (no generated dir): {paper}")
            continue
        status_path = generated / "lean_status.tex"
        status_path.write_text(render_paper_status(manifest, paper))
        suffix = "" if paper in claimed else "  (emptied: no manifest claims)"
        print(f"wrote {status_path}{suffix}")

    print(f"manifest_hash={manifest['content_hash']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
