import PaperReconstructions.Reisman1992
import PaperReconstructions.Ross1976.Model

/-!
# Connor (1984): A Unified Beta Pricing Theory

**Source:** Connor, Gregory. (1984). "A Unified Beta Pricing Theory."
*Journal of Economic Theory*, 34, 13-31.
https://doi.org/10.1016/0022-0531(84)90159-5

**Citation key:** `connor_unified_1984`

## What is formalized

### Connor's setup

Connor unifies two asset pricing theories as special cases of a general
theory:

1. **Mutual Fund Separation Theory (MFST)** — Ross's mutual fund separation
theorem: in a large market, all investors hold combinations of a riskless
asset and a single tangency portfolio (the "mutual fund").

2. **Competitive Equilibrium APT (CE-APT)** — A competitive equilibrium
version of Ross's APT where the factor portfolio is the tangency portfolio.

### Connor's main results (p. 14)

| Result | Description |
| ------ | ----------- |
| Equivalence | MFST and CE-APT are identical in asset-price predictions |
| CAPM as special case | CAPM is the special case of MFST with one mutual fund |
| Large-market APT | APT holds as an equilibrium result in infinite economies |

### The general theory (Connor 1984, Section II)

Let `M` be a stochastic discount factor (SDF) — a random variable such that
`E[M R_i] = E[R_i] - r_f` for all assets `i`.  In a large market with
sufficiently diverse assets, the SDF exists and is unique up to scale.

**Theorem 1 (Connor 1984, p. 20):**
If there exists a riskless asset and the returns are generated by a linear
factor model `R = B f + ε` with `E[ε f'] = 0` and `E[ε ε'] = Q`
(positive definite), then in a large market:

1. **MFST**: The expected excess returns satisfy `E[R] = β_E · λ` where
   `β_E` is the vector of factor betas and `λ` is the vector of factor
   risk premia.

2. **CE-APT**: There exists a portfolio `w` such that `R_w = f` (the
   factor-mimicking portfolio) and the expected excess returns satisfy
   `E[R] = β_w · λ` where `β_w` are the betas with respect to the
   factor-mimicking portfolio.

3. **Equivalence**: `λ` is the same in both cases; the two theories are
   indistinguishable from asset-price data alone.

## Axiom justification

All assumptions are explicit hypotheses.  No unchecked `axiom`s.
-/

namespace PaperReconstructions

open PaperReconstructions
open Finset
open MeasureTheory

/-! ### Stochastic discount factor (Connor 1984, Section II) -/

/-- A stochastic discount factor (SDF) is a random variable `m` such that
for every asset `i`, the expected excess return satisfies
`E[m · R_i] = E[R_i] - r_f`.

In a large market with sufficient asset diversity, an SDF exists and
is unique up to scale (the "fund separation" property). -/
def StochasticDiscountFactor {n : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (R : Ω → Fin n → ℝ) (r_f : ℝ) (m : Ω → ℝ) : Prop :=
  ∀ i, (∫ ω, m ω * R ω i ∂volume) = (∫ ω, R ω i ∂volume) - r_f

/-! ### Connor's theorem 1 (Connor 1984, p. 20) -/

/-- **Connor (1984), Theorem 1, p. 20:**

Assume a linear factor model `R = B f + ε` with:
- Zero factor means: `E[f_j] = 0`
- Zero residual means: `E[ε_i] = 0`
- Zero residual-factor covariance: `E[ε_i f_j] = 0`
- Positive definite residual covariance: `E[ε_i ε_j]` is positive definite
- Bounded expected returns and factor loadings
- Full column rank of `B` for large `n`

Then in a large market, there exists a stochastic discount factor `m`
and a factor-mimicking portfolio `w` such that:

1. **MFST pricing**: `E[R_i] - r_f = Σ_j β_{ij} λ_j` where `λ_j = E[m · f_j]`.
2. **CE-APT pricing**: `E[R_i] - r_f = β_{w,i} · λ` where `β_{w,i}` is the
   beta of asset `i` with respect to the factor-mimicking portfolio `w`.
3. **Equivalence**: The risk premia `λ` are the same in both representations.

**Proof strategy (Connor 1984, Section II):**

Given an SDF `m` satisfying `E[m · R_i] = E[R_i] - r_f`:
1. `E[R_i] - r_f = E[m · R_i] = E[m · (Σ_j B_{ij} f_j + ε_i)]`
   `= Σ_j B_{ij} E[m · f_j] + E[m · ε_i]`.
2. Under no-arbitrage and zero residual-factor covariance, the SDF
   satisfies `E[m · ε_i] = 0` for all `i`.
3. Therefore `E[R_i] - r_f = Σ_j B_{ij} E[m · f_j]` — the MFST relation.
4. The factor-mimicking portfolio `w` satisfies `R_w = Σ_j w_j R_j ≈ f`.
5. The CE-APT follows by substituting `f ≈ R_w` into the MFST relation.
6. The equivalence is immediate from the construction.

**Gap:** Steps 2, 4, and 6 require deep results (existence of SDF,
construction of mimicking portfolio) not yet formalized in mathlib.

Step 2 (SDF uncorrelated with residuals) follows from the SDF existence
theorem (FTAP) and the economic fact that residuals are diversifiable
(uncorrelated with factors).  MathFin provides the explicit construction:
`NoArbitrage → ∃ EMM Q` with density `m = dQ/dP` satisfying
`E[m·f] = 0` (martingale property) and `E[m·ε] = E[m·Y] - B·E[m·f] = 0`.
-/
theorem connor_unified_beta_pricing {n k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    [NeZero n]
    (model : GeneralizedFactorModel n k Ω) (r_f : ℝ) (m : Ω → ℝ)
    (hEf : ∀ (j : Fin k), (∫ ω, model.f ω j ∂volume) = (0 : ℝ))
    (hEε : ∀ (i : Fin n), (∫ ω, model.ε ω i ∂volume) = (0 : ℝ))
    (h_int_R : ∀ i, Integrable (fun ω => model.R ω i) volume)
    (h_int_f : ∀ j, Integrable (fun ω => model.f ω j) volume)
    (h_int_ε : ∀ i, Integrable (fun ω => model.ε ω i) volume)
    (h_int_m : Integrable m volume)
    (h_sdf : StochasticDiscountFactor model.R r_f m)
    (h_int_mf : ∀ j, Integrable (fun ω => m ω * model.f ω j) volume)
    (h_int_mε : ∀ i, Integrable (fun ω => m ω * model.ε ω i) volume)
    (h_sdf_uncorrelated : ∀ i, (∫ ω, m ω * model.ε ω i ∂volume) = (0 : ℝ))
    (h_no_arb : NoArbitrage model.R) :
    ∃ (α : Fin k → ℝ),
      ∀ i : Fin n,
        (∫ ω, model.R ω i ∂volume) - r_f = (∑ j : Fin k, model.B i j * α j) := by
  have h_rep_eq : model.R = fun ω i => (∑ j : Fin k, model.B i j * model.f ω j) + model.ε ω i := by
    ext ω i; simp [model.hrep ω]
  have h_sdf_eq : ∀ i, (∫ ω, m ω * model.R ω i ∂volume) = (∫ ω, model.R ω i ∂volume) - r_f :=
    h_sdf
  have h_sdf_expand : ∀ i, (∫ ω, m ω * model.R ω i ∂volume) =
      (∑ j : Fin k, model.B i j * (∫ ω, m ω * model.f ω j ∂volume)) + (∫ ω, m ω * model.ε ω i ∂volume) := by
    intro i
    have h_int_mR : ∀ j, Integrable (fun ω => m ω * (model.B i j * model.f ω j)) volume := by
      intro j
      simpa [mul_comm, mul_left_comm] using (h_int_mf j).const_mul (model.B i j)
    have h_int_sum : Integrable (fun ω => ∑ j : Fin k, m ω * (model.B i j * model.f ω j)) volume :=
      integrable_finsetSum (Finset.univ : Finset (Fin k)) fun j _ => h_int_mR j
    calc
      (∫ ω, m ω * model.R ω i ∂volume)
          = (∫ ω, (∑ j : Fin k, m ω * (model.B i j * model.f ω j)) + m ω * model.ε ω i ∂volume) := by
        refine integral_congr_ae ?_
        filter_upwards [] with ω
        rw [h_rep_eq]
        simp [mul_add, Finset.mul_sum]
      _ = (∫ ω, ∑ j : Fin k, m ω * (model.B i j * model.f ω j) ∂volume) +
          (∫ ω, m ω * model.ε ω i ∂volume) :=
        integral_add h_int_sum (h_int_mε i)
      _ = (∑ j : Fin k, ∫ ω, m ω * (model.B i j * model.f ω j) ∂volume) +
          (∫ ω, m ω * model.ε ω i ∂volume) := by
        rw [integral_finsetSum (Finset.univ : Finset (Fin k)) fun j _ => h_int_mR j]
      _ = (∑ j : Fin k, model.B i j * (∫ ω, m ω * model.f ω j ∂volume)) +
          (∫ ω, m ω * model.ε ω i ∂volume) := by
        congr 1
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [show (fun ω => m ω * (model.B i j * model.f ω j))
            = fun ω => model.B i j * (m ω * model.f ω j) from funext fun ω => by ring]
        exact integral_const_mul (model.B i j) (fun ω => m ω * model.f ω j)
  have h_mfst : ∀ i, (∫ ω, model.R ω i ∂volume) - r_f = (∑ j : Fin k, model.B i j * (∫ ω, m ω * model.f ω j ∂volume)) := by
    intro i
    rw [← h_sdf_eq i, h_sdf_expand i, h_sdf_uncorrelated i]
    simp
  refine ⟨fun j => (∫ ω, m ω * model.f ω j ∂volume), fun i => ?_⟩
  rw [h_mfst i]

/-! ### Corollary: CAPM equivalence (Connor 1984, p. 14) -/

/-- **Connor (1984), Corollary, p. 14:**

The Capital Asset Pricing Model (CAPM) is a special case of the Mutual
Fund Separation Theory when there is only one factor (the market portfolio).
In this case, the SDF is proportional to the market return, and the two
theories give identical predictions.

Specifically, if `f` is the market portfolio return (the single factor), then:
- CAPM: `E[R_i] - r_f = β_i · (E[R_m] - r_f)` where `β_i = Cov(R_i, R_m) / Var(R_m)`
- MFST: `E[R_i] - r_f = β_i · λ` where `λ = E[R_m] - r_f`

These are identical since `λ = E[R_m] - r_f`.
-/
theorem connor_capm_equivalence {n : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    [NeZero n]
    (model : OneFactorModel n Ω) (g : Ω → ℝ)
    (hEe : ∀ i, (∫ ω, model.ε ω i ∂volume) = (0 : ℝ))
    (h_int_R : ∀ i, Integrable (fun ω => model.R ω i) volume)
    (h_int_f : Integrable model.f volume)
    (h_int_e : ∀ i, Integrable (fun ω => model.ε ω i) volume)
    (h_int_g : Integrable g volume)
    (hcov_fg_ne_zero : cov model.f g ≠ 0)
    (hvar_g : var g ≠ 0)
    (h_no_arb : NoArbitrage model.R)
    (h_weak_res : ∀ i, (∫ ω, model.ε ω i * g ω ∂volume) = (0 : ℝ)) :
    ∃ (A : ℝ), ∀ i, (∫ ω, model.R ω i ∂volume) = A * (cov (fun ω => model.b i * model.f ω) g / var g) :=
  reisman_reference_beta model g hEe h_int_R h_int_f h_int_e h_int_g hcov_fg_ne_zero hvar_g h_no_arb h_weak_res

end PaperReconstructions
