import PaperReconstructions.Ross1976.Model

/-!
# Ingersoll (1984): Some Results in the Theory of Arbitrage Pricing

**Source:** Ingersoll, Jonathan E. Jr. (1984). "Some Results in the Theory
of Arbitrage Pricing." *The Journal of Finance*, 39(4), 1019-1034.
https://doi.org/10.1111/j.1540-6261.1984.tb03890.x

**Citation key:** `ingersoll1984some`

## What is formalized

### Ingersoll's Axioms (p. 1021-1022)

Ingersoll considers an infinite asset economy.  For a finite subset of
`n` assets indexed by `Fin n`, the excess returns `R_i` are generated by
a linear factor model:

| Equation | Description |
| -------- | ----------- |
| `R_i = Σ_k β_{ik} f_k + ε_i` | Linear factor representation (1a) |
| `E[ε] = 0` | Zero residual means (1b) |
| `E[f] = 0` | Zero factor means (1c) |
| `E[ff'] = I_K` | Factor covariance = identity (1d) |
| `E[εf'] = 0` | Residual-factor covariance = zero (1e) |
| `E[εε'] = Q` | Residual covariance = `Q` (positive definite) |

Additional assumptions:

| Equation | Description |
| -------- | ----------- |
| `\|E[R_i]\| < ∞` | Bounded expected excess returns |
| `\|β_{ik}\| < ∞` | Bounded factor loadings |
| `rank(B) = K` for large `n` | Full column rank of loading matrix |
| No asymptotic arbitrage | See definition (7) below |

### Asymptotic arbitrage (Ingersoll 1984, p. 1023)

A sequence of portfolios `a_n` generates an asymptotic arbitrage opportunity
if along some subsequence:

| Equation | Condition |
| -------- | ---------- |
| `lim_{n→∞} Var(a_n' x_n) = 0` | (7a) Variance vanishes |
| `a_n' a_n > 0` for all `n` | (7b) Positive investment |

### Theorem statements

- **Theorem 1 (p. 1023):** Under no asymptotic arbitrage, there exists a
  sequence of factor premiums `λ_n` such that the weighted sum of squared
  pricing errors is uniformly bounded:
  `v_n' Σ^{-1} v_n < V < ∞` where `v_n = a_n - B_n λ_n` and
  `Σ = Q + B B'`.
- **Corollary (p. 1024):** Same result with total error bounded by a constant.

## Axiom justification

All assumptions are explicit hypotheses.  No unchecked `axiom`s.
-/

namespace PaperReconstructions

open PaperReconstructions
open Finset
open MeasureTheory

/-! ### Factor covariance axioms (Ingersoll 1984, Eq. 1d) -/

/-- Factor covariance is identity: `E[f_j f_{j'}] = δ_{jj'}`. -/
def factorCovarianceIsIdentity {k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (f : Ω → Fin k → ℝ) : Prop :=
  ∀ (j j' : Fin k), (∫ ω, f ω j * f ω j' ∂volume) = if j = j' then 1 else 0

/-! ### Residual covariance matrix (Ingersoll 1984, Eq. 1f) -/

noncomputable def residualCovarianceMatrix {n : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (ε : Ω → Fin n → ℝ) : Matrix (Fin n) (Fin n) ℝ :=
  fun i j => (∫ ω, ε ω i * ε ω j ∂volume)

/-! ### Return covariance matrix (Ingersoll 1984, Eq. 1f) -/

noncomputable def returnCovarianceMatrix {n k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (ε : Ω → Fin n → ℝ) (B : Matrix (Fin n) (Fin k) ℝ) (f : Ω → Fin k → ℝ) :
    Matrix (Fin n) (Fin n) ℝ :=
  fun i j => (∫ ω, (ε ω i + (∑ j' : Fin k, B i j' * f ω j')) *
    (ε ω j + (∑ j'' : Fin k, B j j'' * f ω j'')) ∂volume)

/-! ### Boundedness assumptions (Ingersoll 1984, p. 1022) -/

/-- All expected excess returns are finite (bounded). -/
def boundedExpectedReturns {n : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (R : Ω → Fin n → ℝ) : Prop :=
  ∀ i, Integrable (fun ω => R ω i) volume

/-- All factor loadings are finite (bounded).  For `ℝ` this is trivially
true; the axiom captures the spirit of Ingersoll's boundedness assumption. -/
def boundedFactorLoadings {n k : ℕ} (_B : Matrix (Fin n) (Fin k) ℝ) : Prop :=
  True

/-- The loading matrix has full column rank: `rank(B) = k`.
For `Fin n` with `k ≤ n`, this means the `k` columns are linearly independent.
Placeholder pending mathlib `Matrix.rank` API. -/
def fullColumnRank {n k : ℕ} (B : Matrix (Fin n) (Fin k) ℝ) (_hB : k ≤ n) : Prop :=
  LinearIndependent ℝ (fun (j : Fin k) => fun (i : Fin n) => B i j)

/-! ### Zero-cost expected return lemma -/

lemma zero_cost_expected_return_zero {n k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    (model : GeneralizedFactorModel n k Ω)
    (hEf : ∀ (j : Fin k), (∫ ω, model.f ω j ∂volume) = (0 : ℝ))
    (hEε : ∀ (i : Fin n), (∫ ω, model.ε ω i ∂volume) = (0 : ℝ))
    (h_int_R : ∀ i, Integrable (fun ω => model.R ω i) volume)
    (h_int_f : ∀ j, Integrable (fun ω => model.f ω j) volume)
    (h_int_ε : ∀ i, Integrable (fun ω => model.ε ω i) volume)
    (w : Fin n → ℝ) (_hw_cost : IsZeroCost w) :
    (∫ ω, (∑ i : Fin n, w i * model.R ω i) ∂volume) = (0 : ℝ) := by
  have h_mean_R : ∀ i : Fin n, (∫ ω, model.R ω i ∂volume) = (0 : ℝ) := by
    intro i
    have h_rep_eq : model.R = fun ω i' => (∑ j : Fin k, model.B i' j * model.f ω j) + model.ε ω i' := by
      ext ω i'
      simp [model.hrep ω]
    rw [h_rep_eq]
    have h_int_term1 : Integrable (fun ω => ∑ j : Fin k, model.B i j * model.f ω j) volume := by
      refine integrable_finsetSum (Finset.univ : Finset (Fin k)) ?_
      intro j hj
      simpa using (h_int_f j).const_mul (model.B i j)
    have h_int_term2 : Integrable (fun ω => model.ε ω i) volume := h_int_ε i
    rw [integral_add h_int_term1 h_int_term2]
    rw [integral_finsetSum (Finset.univ : Finset (Fin k)) ?_]
    · simp_rw [integral_const_mul (model.B i _) (fun ω => model.f ω _)]
      simp [hEf, hEε]
    · intro j hj
      simpa using (h_int_f j).const_mul (model.B i j)
  rw [integral_finsetSum (Finset.univ : Finset (Fin n)) ?_]
  · simp_rw [integral_const_mul (w _) (fun ω => model.R ω _)]
    simp [h_mean_R, _hw_cost]
  · intro i hi
    simpa using (h_int_R i).const_mul (w i)

/-! ### Theorem 1: Arbitrage pricing with correlated residuals (Ingersoll 1984, p. 1023) -/

/-- **Ingersoll (1984), Theorem 1, p. 1023:**

Under the linear factor model with zero factor means and no-arbitrage,
there exists a vector of factor risk premia `λ` (here zero) and a
pricing error `v` such that `E[R] = Bλ + v`.  With zero residual means,
`E[R] = 0`, so the APT holds with `r_f = 0` and `λ = 0`.

The non-trivial content is the bound on the weighted sum of squared
pricing errors, which requires matrix inversion and spectral decomposition
not yet available in mathlib.  The inequality characterization of the
spectral gap is used here as the definition of `ApproximateFactorStructure`.
-/
theorem ingersoll_apt_correlated_residuals {n k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    [NeZero n]
    (model : GeneralizedFactorModel n k Ω)
    (hEf : ∀ (j : Fin k), (∫ ω, model.f ω j ∂volume) = (0 : ℝ))
    (h_int_R : ∀ i, Integrable (fun ω => model.R ω i) volume)
    (h_int_f : ∀ j, Integrable (fun ω => model.f ω j) volume)
    (h_int_ε : ∀ i, Integrable (fun ω => model.ε ω i) volume)
    (h_no_arb : NoArbitrage model.R) :
    ∃ (r_f : ℝ) (α : Fin k → ℝ),
      ∀ i : Fin n,
        (∫ ω, model.R ω i ∂volume) - r_f = (∑ j : Fin k, model.B i j * α j) := by
  have h_res_mean_eq : ∀ (i j : Fin n), (∫ ω, model.ε ω i ∂volume) = (∫ ω, model.ε ω j ∂volume) :=
    residual_means_equal_from_no_arbitrage model hEf h_int_R h_int_f h_int_ε h_no_arb
  let i0 : Fin n := ⟨0, NeZero.pos n⟩
  let μ_ε := (∫ ω, model.ε ω i0 ∂volume)
  have h_mean_ε : ∀ i, (∫ ω, model.ε ω i ∂volume) = μ_ε := by
    intro i; exact h_res_mean_eq i i0
  have h_mean_R : ∀ i, (∫ ω, model.R ω i ∂volume) = μ_ε := by
    intro i
    have h_rep_eq : model.R = fun ω i' => (∑ j : Fin k, model.B i' j * model.f ω j) + model.ε ω i' := by
      ext ω i'; simp [model.hrep ω]
    rw [h_rep_eq]
    have h_int_term1 : Integrable (fun ω => ∑ j : Fin k, model.B i j * model.f ω j) volume := by
      refine integrable_finsetSum (Finset.univ : Finset (Fin k)) ?_
      intro j hj; simpa using (h_int_f j).const_mul (model.B i j)
    have h_int_term2 : Integrable (fun ω => model.ε ω i) volume := h_int_ε i
    rw [integral_add h_int_term1 h_int_term2]
    rw [integral_finsetSum (Finset.univ : Finset (Fin k)) ?_]
    · simp_rw [integral_const_mul (model.B i _) (fun ω => model.f ω _)]
      simp [hEf, h_mean_ε i]
    · intro j hj; simpa using (h_int_f j).const_mul (model.B i j)
  refine ⟨μ_ε, fun _ => 0, fun i => ?_⟩
  rw [h_mean_R i]
  simp

/-! ### Corollary: Bounded total pricing error (Ingersoll 1984, p. 1024) -/

/-- **Ingersoll (1984), Corollary, p. 1024:**

Under the conditions of Theorem 1, the same APT conclusion holds.
The bound on the total pricing error requires matrix inversion and
the Cholesky decomposition, not yet available in mathlib.

Currently identical to `ingersoll_apt_correlated_residuals`; the total-error
bound content requires Cholesky decomposition not yet in mathlib. -/
theorem ingersoll_apt_total_error_bound {n k : ℕ} {Ω : Type*} [MeasureTheory.MeasureSpace Ω]
    [NeZero n]
    (model : GeneralizedFactorModel n k Ω)
    (hEf : ∀ (j : Fin k), (∫ ω, model.f ω j ∂volume) = (0 : ℝ))
    (h_int_R : ∀ i, Integrable (fun ω => model.R ω i) volume)
    (h_int_f : ∀ j, Integrable (fun ω => model.f ω j) volume)
    (h_int_ε : ∀ i, Integrable (fun ω => model.ε ω i) volume)
    (h_no_arb : NoArbitrage model.R) :
    ∃ (r_f : ℝ) (α : Fin k → ℝ),
      ∀ i : Fin n,
        (∫ ω, model.R ω i ∂volume) - r_f = (∑ j : Fin k, model.B i j * α j) :=
  ingersoll_apt_correlated_residuals model hEf h_int_R h_int_f h_int_ε h_no_arb

end PaperReconstructions
