"""Build the schematic field geometry and matching identity assets (stdlib only).

Run from the portfolio directory: python scripts/generate-field-art.py
These are illustrative Gaussian fields, not fitted economic observations.
The browser animates two SVG groups; it never evaluates the field.
"""

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPER, INK, SIGNAL = "#faf9f4", "#00243a", "#006590"


def simplify(points, tolerance=.25):
    """Preserve subpixel accuracy without shipping the full sampling grid."""
    if len(points) < 3:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    length = math.hypot(dx, dy)
    distances = [(abs(dy * (p[0] - a[0]) - dx * (p[1] - a[1])) / length
                  if length else math.dist(a, p)) for p in points[1:-1]]
    maximum = max(distances)
    if maximum <= tolerance:
        return [a, b]
    index = distances.index(maximum) + 1
    return simplify(points[:index + 1], tolerance)[:-1] + simplify(points[index:], tolerance)


def field(x, y):
    # Two economic regions joined by a broad, low-frequency mode.
    u, v = (x - 320) / 175, (y - 306) / 175
    return (math.exp(-((u + .52) ** 2 / .57 + (v + .42) ** 2 / .9))
            + .88 * math.exp(-((u - .64) ** 2 / .65 + (v - .65) ** 2 / .44)))


def contour(level):
    segments = []
    step = 6
    for y in range(30, 582, step):
        for x in range(26, 614, step):
            points = [(x, y), (x + step, y), (x + step, y + step), (x, y + step)]
            values = [field(*p) for p in points]
            hits = []
            for i in range(4):
                j = (i + 1) % 4
                if (values[i] < level) != (values[j] < level):
                    t = (level - values[i]) / (values[j] - values[i])
                    hits.append(tuple(round(points[i][k] + t * (points[j][k] - points[i][k]), 2) for k in (0, 1)))
            if len(hits) == 2:
                segments.append(hits)
    neighbours = {}
    for a, b in segments:
        neighbours.setdefault(a, []).append(b)
        neighbours.setdefault(b, []).append(a)
    paths = []
    while neighbours:
        start = next((p for p, n in neighbours.items() if len(n) == 1), next(iter(neighbours)))
        current, chain = start, [start]
        while current in neighbours and neighbours[current]:
            target = neighbours[current].pop()
            if not neighbours[current]:
                del neighbours[current]
            neighbours[target].remove(current)
            if not neighbours[target]:
                del neighbours[target]
            chain.append(target)
            current = target
        # Keep the sampled curves precise and avoid excessive SVG precision.
        d = "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in simplify(chain))
        if chain[-1] == chain[0]:
            d += "Z"
        paths.append(d)
    return " ".join(paths)


paths = [contour(.10 + i * .075) for i in range(14)]
data = "// Generated by scripts/generate-field-art.py; schematic, not empirical.\n"
data += "export const fieldContours = " + json.dumps(paths, indent=2) + ";\n"
(ROOT / "src/components/field-geometry.ts").write_text(data)

# A compact pair of extended measures sharing a middle isobath.
# Three open curves remain distinct at 16px; no miniature hero details.
mark = ('<g fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round">'
        '<path d="M10 24C16 24 17 12 26 12S36 24 42 24"/>'
        '<path d="M10 32C18 32 19 24 26 24S34 32 42 32"/>'
        '<path d="M10 40C16 40 17 52 26 52S36 40 42 40"/>'
        '</g>')
# Centre the asymmetric-width drawing in its square.
mark = '<g transform="translate(6 0)">' + mark + '</g>'
for name, body in [
    ("atlas-mark.svg", f'<g color="{INK}">{mark}</g>'),
    ("favicon.svg", f'<rect width="64" height="64" rx="12" fill="{INK}"/><g color="{PAPER}">{mark}</g>'),
]:
    (ROOT / "public/icons" / name).write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
        '<title>Pricing Perspective — shared field</title>' + body + '</svg>\n')

linework = ''.join(f'<path d="{d}" opacity="{.28 if i % 3 else .6}"/>' for i, d in enumerate(paths))
footprints = ''.join(
    f'<g transform="translate({x} {y}) rotate({a})"><ellipse rx="{rx}" ry="{ry}" fill="{PAPER}" fill-opacity=".88" stroke="{INK}" stroke-width="1.8"/>'
    f'<ellipse rx="{rx-8}" ry="{ry-8}" fill="{SIGNAL}" fill-opacity=".10" stroke="{SIGNAL}" stroke-width=".7"/>'
    f'<path d="M-5 0H5M0-5V5" stroke="{INK}"/></g>'
    for x, y, a, rx, ry in [(230, 238, -32, 56, 29), (328, 313, 38, 78, 31), (427, 395, -24, 45, 27)]
)
art = (f'<g fill="none" stroke="{SIGNAL}" stroke-width="1">{linework}</g>' + footprints)
svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 620">'
(ROOT / "public/og/hydrographic-atlas.svg").write_text(svg + '<title>Shared economic field and firm footprints — schematic</title>' + art + '</svg>\n')
card = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
<title>Pricing Perspective — shared fields, distinct exposures</title>
<rect width="1200" height="630" fill="{PAPER}"/>
<path d="M48 48H1152M48 582H1152" stroke="{INK}" stroke-opacity=".25"/>
<g transform="translate(640 26) scale(.88)">{art}</g>
<g fill="{INK}">
<text x="64" y="106" font-family="monospace" font-size="15" letter-spacing="3">PRICING PERSPECTIVE</text>
<text x="60" y="252" font-family="Georgia,serif" font-size="52">Firms are not points.</text>
<text x="60" y="321" font-family="Georgia,serif" font-size="44">Their relationships</text>
<text x="60" y="379" font-family="Georgia,serif" font-size="44" font-style="italic">have geometry.</text>
<text x="64" y="467" font-family="sans-serif" font-size="18">Information, geometry, and pricing.</text>
<text x="64" y="551" font-family="sans-serif" font-size="16">Marcus Gawronsky · Chun-Sung Huang</text>
</g></svg>'''
(ROOT / "public/og/atlas-card.svg").write_text(card + '\n')
print(f"Generated {len(paths)} contours; {len(data):,} bytes of geometry.")
