[doc]
name = "05_spatial_pricing"
bundle = "../../bundle/tlextras-2022.0r0-pricing-perspective.zip"

[[output]]
name = "draft"
type = "pdf"
inputs = ["targets/draft.tex"]

[[output]]
name = "arxiv"
type = "pdf"
inputs = ["targets/arxiv.tex"]
