[doc]
name = "05_spatial_pricing"
bundle = "../../bundle/tlextras-2022.0r0-pricing-perspective.zip"

[[output]]
name = "draft"
type = "pdf"
inputs = ["targets/draft.tex"]

[[output]]
name = "arxiv"
type = "pdf"
inputs = ["targets/arxiv.tex"]

[[output]]
name = "quantitative-finance"
type = "pdf"
inputs = ["targets/quantitative-finance.tex"]

[[output]]
name = "jfec"
type = "pdf"
inputs = ["targets/jfec.tex"]

[[output]]
name = "jfec-letter"
type = "pdf"
inputs = ["targets/jfec/letter.tex"]
