import PricingPerspective.Transmission.Defs

set_option linter.style.longLine false

open Finset
open scoped InnerProductSpace

/-!
# Finite factor-return covariance bridge

This file makes the finite factor-return covariance bridge explicit. Factor
innovations are represented by a mean-zero isotropic finite law, while
cross-residual orthogonality is an explicit premise for residual covariance
claims; no probabilistic independence is derived here.
-/

namespace PricingPerspective.RandomExposure

variable {κ H : Type*} [Fintype κ]
variable [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- A finite, mean-zero, isotropic factor law in risk coordinates. -/
structure IsotropicFactor (κ H : Type*) [Fintype κ]
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] where
  /-- Factor-state probability weights. -/
  weight : κ → ℝ
  /-- Factor realization at each state. -/
  value : κ → H
  /-- Factor weights are nonnegative. -/
  nonneg : ∀ k, 0 ≤ weight k
  /-- Factor weights have unit mass. -/
  mass_one : ∑ k, weight k = 1
  /-- The factor has zero mean. -/
  mean_zero : ∑ k, weight k • value k = 0
  /-- Risk-coordinate covariance is the Hilbert inner product. -/
  isotropic : ∀ u v,
    ∑ k, weight k * (⟪u, value k⟫_ℝ * ⟪v, value k⟫_ℝ) = ⟪u, v⟫_ℝ

namespace IsotropicFactor

variable (F : IsotropicFactor κ H)

/-- The finite factor mean, exposed for downstream return statements. -/
def mean : H := ∑ k, F.weight k • F.value k

@[simp] theorem mean_eq_zero : F.mean = 0 := F.mean_zero

end IsotropicFactor

/-- Weighted expectation of a scalar finite random variable under `F`. -/
def weightedMean (F : IsotropicFactor κ H) (x : κ → ℝ) : ℝ :=
  ∑ k, F.weight k * x k

/-- Weighted mean of one residual field under the factor law. -/
def residualMean (F : IsotropicFactor κ H) (ε : κ → ℝ) : ℝ :=
  weightedMean F ε

/-- Cross-residual orthogonality under one finite factor law. -/
structure ResidualCrossOrthogonality
    (F : IsotropicFactor κ H)
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ) where
  /-- Every left residual field has zero weighted mean. -/
  left_mean_zero : ∀ a, residualMean F (ε a) = 0
  /-- Every right residual field has zero weighted mean. -/
  right_mean_zero : ∀ b, residualMean F (η b) = 0
  /-- Every pair of residual fields has zero weighted cross moment. -/
  cross_zero : ∀ a b,
    weightedMean F (fun k => ε a k * η b k) = 0
/-- A factor projection has zero weighted mean under the factor premise. -/
theorem weightedMean_factor_projection_eq_zero
    (F : IsotropicFactor κ H) (u : H) :
    weightedMean F (fun k => ⟪u, F.value k⟫_ℝ) = 0 := by
  unfold weightedMean
  calc
    ∑ k, F.weight k * ⟪u, F.value k⟫_ℝ =
        ⟪u, ∑ k, F.weight k • F.value k⟫_ℝ := by
      rw [inner_sum]
      simp_rw [real_inner_smul_right]
    _ = 0 := by rw [F.mean_zero]; simp

/-- Mean return of an exposure cloud against a finite factor law. -/
def factorReturnMean {ι : Type*} [Fintype ι]
    (p : ι → ℝ) (F : IsotropicFactor κ H) (Z : ι → H) : ℝ :=
  ∑ a, p a * ⟪Z a, F.mean⟫_ℝ

/-- Raw cross moment of two loading clouds under one coupling and one factor law. -/
def factorReturnRawCross {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H) : ℝ :=
  ∑ a, ∑ b, ∑ k,
    π.w a b * F.weight k *
      (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ)

/-- Covariance of factor returns generated by a coupling of loading clouds. -/
def factorReturnCovariance {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H) : ℝ :=
  factorReturnRawCross π F Z Y -
    factorReturnMean p F Z * factorReturnMean q F Y
/-- Centered coupling-weighted cross covariance of two residual fields. -/
def residualCrossCovariance
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ) : ℝ :=
  ∑ a, ∑ b, ∑ k,
    π.w a b * F.weight k *
      ((ε a k - residualMean F (ε a)) *
        (η b k - residualMean F (η b)))

/-- Centered factor--residual covariance, including both cross terms. -/
def factorResidualCrossCovariance
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H)
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ) : ℝ :=
  ∑ a, ∑ b, ∑ k,
    π.w a b * F.weight k *
      (⟪Z a, F.value k⟫_ℝ * (η b k - residualMean F (η b)) +
        (ε a k - residualMean F (ε a)) * ⟪Y b, F.value k⟫_ℝ)
/-- Full centered return covariance with residual and factor--residual terms. -/
def factorReturnCovarianceWithResidual
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H)
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ) : ℝ :=
  factorReturnCovariance π F Z Y +
    residualCrossCovariance π F ε η +
    factorResidualCrossCovariance π F Z Y ε η


/-- The finite factor-return mean vanishes under the explicit zero-mean premise. -/
theorem factorReturnMean_eq_zero {ι : Type*} [Fintype ι]
    (p : ι → ℝ) (F : IsotropicFactor κ H) (Z : ι → H) :
    factorReturnMean p F Z = 0 := by
  unfold factorReturnMean IsotropicFactor.mean
  rw [F.mean_zero]
  simp

/-- The raw factor-return cross moment equals the coupling covariance form. -/
theorem factorReturnRawCross_eq_systCov
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H) :
    factorReturnRawCross π F Z Y = systCov π Z Y := by
  unfold factorReturnRawCross systCov
  calc
    (∑ a, ∑ b, ∑ k,
        π.w a b * F.weight k *
          (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ)) =
        ∑ a, ∑ b, π.w a b *
          ∑ k, F.weight k *
            (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ) := by
      refine Finset.sum_congr rfl fun a _ => ?_
      refine Finset.sum_congr rfl fun b _ => ?_
      calc


        (∑ k, π.w a b * F.weight k *
            (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ)) =
            ∑ k, π.w a b *
              (F.weight k *
                (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ)) := by
          apply Finset.sum_congr rfl
          intro k hk
          ring
        _ = π.w a b *
              ∑ k, F.weight k *
                (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ) := by
          exact (Finset.mul_sum (Finset.univ : Finset κ)
            (fun k => F.weight k *
              (⟪Z a, F.value k⟫_ℝ * ⟪Y b, F.value k⟫_ℝ)) (π.w a b)).symm
    _ = ∑ a, ∑ b, π.w a b * ⟪Z a, Y b⟫_ℝ := by
      refine Finset.sum_congr rfl fun a _ => ?_
      refine Finset.sum_congr rfl fun b _ => ?_
      rw [F.isotropic]
/-- Residual cross covariance vanishes under an explicit cross-orthogonality
    premise; this theorem does not derive orthogonality from independence. -/
theorem residualCrossCovariance_eq_zero_of_cross_orthogonality
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ)
    (A : ResidualCrossOrthogonality F (p := p) (q := q) ε η) :
    residualCrossCovariance π F ε η = 0 := by
  have hzero : ∀ a b, ∑ k, F.weight k * (ε a k * η b k) = 0 := by
    intro a b
    simpa [weightedMean] using A.cross_zero a b
  unfold residualCrossCovariance
  simp only [A.left_mean_zero, A.right_mean_zero, sub_zero]
  calc
    (∑ a, ∑ b, ∑ k, π.w a b * F.weight k * (ε a k * η b k)) =
        ∑ a, ∑ b, π.w a b *
          ∑ k, F.weight k * (ε a k * η b k) := by
      refine Finset.sum_congr rfl fun a _ => ?_
      refine Finset.sum_congr rfl fun b _ => ?_
      calc
        (∑ k, π.w a b * F.weight k * (ε a k * η b k)) =
            ∑ k, π.w a b * (F.weight k * (ε a k * η b k)) := by
          apply Finset.sum_congr rfl
          intro k hk
          ring
        _ = π.w a b * ∑ k, F.weight k * (ε a k * η b k) :=
          (Finset.mul_sum (Finset.univ : Finset κ)
            (fun k => F.weight k * (ε a k * η b k)) (π.w a b)).symm
    _ = 0 := by simp [hzero]

/-- Under the explicit factor assumptions, return covariance is `systCov`. -/
theorem factorReturnCovariance_eq_systCov
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H) :
    factorReturnCovariance π F Z Y = systCov π Z Y := by
  unfold factorReturnCovariance
  rw [factorReturnRawCross_eq_systCov,
    factorReturnMean_eq_zero p F Z, factorReturnMean_eq_zero q F Y]
  ring
/-- Under explicit residual and factor--residual premises, total covariance is
    the systematic covariance; no probabilistic independence is claimed. -/
theorem factorReturnCovarianceWithResidual_eq_systCov_of_cross_orthogonality
    {ι ι' : Type*} [Fintype ι] [Fintype ι']
    {p : ι → ℝ} {q : ι' → ℝ}
    (π : Coupling p q) (F : IsotropicFactor κ H)
    (Z : ι → H) (Y : ι' → H)
    (ε : ι → κ → ℝ) (η : ι' → κ → ℝ)
    (A : ResidualCrossOrthogonality F (p := p) (q := q) ε η)
    (hfactor : factorResidualCrossCovariance π F Z Y ε η = 0) :
    factorReturnCovarianceWithResidual π F Z Y ε η = systCov π Z Y := by
  unfold factorReturnCovarianceWithResidual
  rw [residualCrossCovariance_eq_zero_of_cross_orthogonality π F ε η A,
    hfactor, factorReturnCovariance_eq_systCov π F Z Y]
  ring

end PricingPerspective.RandomExposure
