"""Paper 1 sample-descriptives table rendering."""

from __future__ import annotations

from pathlib import Path
from typing import cast

import yaml

from pipeline.figures.paper1._tables.format import _sector_row

_DEFAULT_SUMMARY = Path("data/papers/paper1/sample_descriptives/summary.yaml")
_DEFAULT_OUTPUT = Path(
    "src/latex/projects/01_continuous_bounds/src/generated/sample_descriptives.tex"
)


def _render_sector_table(summary: dict[str, object]) -> str:
    sectors = cast("dict[str, dict[str, object]]", summary["sectors"])
    overall = cast("dict[str, object]", summary["overall"])

    lines = [
        r"\small",
        r"\begin{tabularx}{\linewidth}{Xrrrrr}",
        r"\toprule",
        (
            r"Sector & $n$ & Articles & Volatility & "
            r"$W_2$ within & $W_2$ cross \\"
        ),
        r"\midrule",
    ]
    lines.extend(_sector_row(sector, sectors[sector]) for sector in sorted(sectors))
    lines.extend(
        (
            r"\midrule",
            _sector_row(
                "All sectors",
                {
                    "n_firms": overall["n_firms"],
                    "mean_articles_per_firm": overall["mean_articles_per_firm"],
                    "mean_daily_return_volatility": overall.get(
                        "mean_daily_return_volatility"
                    ),
                    "mean_within_sector_w2_distance": overall.get(
                        "mean_within_sector_w2_distance"
                    ),
                    "mean_cross_sector_w2_distance": overall.get(
                        "mean_cross_sector_w2_distance"
                    ),
                },
            ),
        )
    )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabularx}")
    return "\n".join(lines)


_PAPER1_CAPTION = (
    r"Per-sector sample composition: firm count, mean article "
    r"count per firm, mean daily return volatility, and mean within- "
    r"versus cross-sector pairwise rooted $W_2$ distance. Articles are "
    r"subsampled to a fixed per-firm cap, so counts are near-constant "
    r"by construction. A dash indicates a statistic that is undefined "
    r"for that sector (e.g.\ within-sector distance for a singleton "
    r"sector). Authors' calculations."
)


def render_sample_descriptives_table(
    summary_file: Path = _DEFAULT_SUMMARY,
    output_file: Path = _DEFAULT_OUTPUT,
    caption: str = _PAPER1_CAPTION,
    label: str = "tab:sample-descriptives-sectors",
    generator: str = "pipeline render-paper1-tables",
) -> str:
    """Render the sample-descriptives fragment from ``summary_file``.

    Write it to ``output_file`` and return the fragment text.

    Volatility is displayed to 4 decimal places (daily scale, matching the
    ``units`` documentation in the summary YAML — not annualised). Article
    counts to 1 decimal place (means/medians over integer counts). W2
    distances to 3 decimal places, matching the precision used elsewhere in
    Paper 1's generated numbers for this quantity.

    ``caption``, ``label`` and ``generator`` are parameters because Papers 1
    and 5 tabulate the same statistics over different encoders and must not
    share a float label or claim the same producer. The defaults reproduce
    Paper 1's fragment byte for byte.
    """
    with Path(summary_file).open(encoding="utf-8") as fh:
        summary = yaml.safe_load(fh)

    sector_table = _render_sector_table(summary)
    sector_caption = rf"\caption{{{caption}}}"
    fragment = (
        f"% AUTO-GENERATED by {generator} -- do not edit by hand.\n\n"
        r"\begin{table}[H]"
        "\n\n"
        r"\centering"
        f"\n\n{sector_table}\n\n{sector_caption}\n\n"
        rf"\label{{{label}}}"
        "\n\n"
        r"\end{table}"
    )
    fragment += "\n"

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(fragment, encoding="utf-8")
    return fragment
