"""Dyadic design-diagnostics table."""

from __future__ import annotations

from typing import TYPE_CHECKING, cast

from pipeline.figures.paper1._tables.dyadic import _validated_primary_spec
from pipeline.figures.paper1._tables.format import (
    _EM_DASH,
    _escape,
    _fmt,
    _fmt_int,
)

if TYPE_CHECKING:
    import pandas as pd


def _render_dyadic_design_diagnostics(
    frame: pd.DataFrame, summary: dict[str, object]
) -> str:
    """Appendix design contract and pre-fit audit for the dyadic ladder."""
    primary_spec_index, primary = _validated_primary_spec(summary)

    bootstrap_draws = int(
        cast("str | bytes | int | float", primary["bootstrap_requested_draws"])
    )
    rows = []
    for _, row in frame.sort_values("spec_index").iterrows():
        dropped_value = row["dropped_columns"]
        if isinstance(dropped_value, (list, tuple)):
            dropped = ", ".join(str(value) for value in dropped_value) or _EM_DASH
        else:
            dropped = _EM_DASH
        rows.append(
            " & ".join(
                [
                    _fmt_int(row["spec_index"]),
                    f"{_fmt_int(row['design_rank'])}/{_fmt_int(row['design_columns'])}",
                    _fmt(row["scaled_condition_number"], 2),
                    _fmt(row["focal_vif"], 2),
                    _fmt(row["focal_fwl_sd_ratio"], 3),
                    _escape(dropped),
                ]
            )
            + r" \\"
        )
    first = frame.iloc[0]
    return "\n".join(
        [
            "% AUTO-GENERATED by pipeline render-paper1-tables -- do not edit by hand.",
            r"\begin{table}[H]",
            r"\centering",
            r"\footnotesize",
            r"\begin{tabularx}{\linewidth}{@{}lX@{}}",
            r"\toprule",
            r"\multicolumn{2}{@{}l}{\textit{Panel A: design contract}} \\",
            r"\midrule",
            (
                r"Sample timing & Pooled news: \ppvalue{sample-year-start}--"
                r"\ppvalue{sample-year-end}; complete-case returns: "
                r"\ppvalue{return-panel-n-observations} common dates, "
                r"\ppvalue{return-panel-date-start}--\ppvalue{return-panel-date-end}. "
                r"News and returns are pooled over the same window. \\"
            ),
            (
                rf"Observational units & {int(frame.iloc[0]['n_nodes'])} firms and "
                rf"{int(frame.iloc[0]['n_dyads'])} unordered dyads $i<j$; one "
                r"observation "
                r"per pair and no self-dyads. \\"
            ),
            (
                r"Metrics & $W_{ij}$ is rooted balanced quadratic Wasserstein "
                r"distance between row-normalized article clouds under Euclidean "
                r"chord ground cost; "
                r"$D_{ij}=\sqrt{2(1-\hat\rho_{ij})}$ from complete-case daily "
                r"returns. \\"
            ),
            (
                rf"Primary design & Specification {primary_spec_index}: "
                r"$D_{ij}=\mu+a_i+a_j+\beta_{W_2} W_{ij}+u_{ij}$, with "
                r"symmetric additive firm effects and one firm indicator "
                r"omitted. \\"
            ),
            (
                rf"Resampling & {bootstrap_draws} multinomial node-bootstrap draws; "
                r"firms are resampled and dyads receive endpoint-multiplicity weight "
                r"$w_iw_j$, "
                r"without artificial self-dyads. \\"
            ),
            (
                r"Estimand & Same-window contemporaneous association conditional on "
                r"realized $W$ and $D$ and additive firm margins. \\"
            ),
            r"\bottomrule",
            r"\end{tabularx}",
            r"\medskip",
            r"\begin{tabularx}{\linewidth}{rrrrrX}",
            r"\toprule",
            (
                r"\multicolumn{6}{l}{\textit{Panel B: pre-fit conditioning by "
                r"ladder rung}} \\"
            ),
            r"\midrule",
            (
                r"Spec. & Rank/cols. & Scaled $\kappa$ & VIF$_{W_2}$ & FWL SD ratio & "
                r"Dropped \\"
            ),
            r"\midrule",
            *rows,
            r"\bottomrule",
            r"\end{tabularx}",
            (
                r"\caption{Dyadic design and pre-fit audit. Panel A fixes the analysis "
                r"sample, metrics, specification, resampling unit, and interpretation "
                r"boundary. Panel B reports conditioning over the complete "
                rf"graph on {int(first['n_nodes'])} firms: "
                rf"{int(first['n_dyads'])} dyads, "
                rf"degree {int(first['degree_min'])} for every firm, and "
                rf"{float(first['endpoint_overlap_share']):.3f} of unordered "
                r"dyad pairs "
                r"share an endpoint. $\kappa$ is computed after centring and unit-norm "
                r"scaling non-intercept columns. VIF$_{W_2}$ and the FWL "
                r"residual-SD ratio "
                r"measure how much W2-distance variation remains after the other "
                r"regressors and summarize numerical conditioning.}"
            ),
            r"\label{tab:dyadic-design-diagnostics}",
            r"\end{table}",
            "",
        ]
    )
