"""Dyadic model-ladder table and its primary-specification guard."""

from __future__ import annotations

from typing import cast

from pipeline.figures.paper1._tables.format import (
    _escape,
    _fmt,
)

_DISPERSION_SPEC_INDEX = 5
_DYADIC_ADJUSTMENT_LABELS = {
    1: "W2 distance only",
    2: "+ same-sector indicator",
    3: "pooled controls",
    4: "+ article-count controls",
    6: "W2 metric + symmetric firm effects",
}


def _render_dyadic_ladder(summary: dict[str, object]) -> str:
    ladder = cast("list[dict[str, object]]", summary.get("model_ladder", []))
    rows_by_spec: dict[int, dict[str, object]] = {}
    for row in ladder:
        spec_index = int(cast("str | bytes | int | float", row["spec_index"]))
        if spec_index in rows_by_spec:
            message = f"duplicate dyadic ladder specification {spec_index}"
            raise ValueError(message)
        rows_by_spec[spec_index] = row

    expected_specs = set(range(1, 7))
    actual_specs = set(rows_by_spec)
    if actual_specs != expected_specs:
        missing = sorted(expected_specs - actual_specs)
        extra = sorted(actual_specs - expected_specs)
        message = (
            "dyadic ladder must contain specifications 1--6; "
            f"missing={missing}, extra={extra}"
        )
        raise ValueError(message)

    panels = (
        (
            r"\multicolumn{8}{l}{\textit{Panel A: staged pooled adjustments}} \\",
            (1, 2, 3, 4, 5),
        ),
        (
            (
                r"\multicolumn{8}{l}{\textit{Panel B: canonical "
                r"endpoint-adjusted specification}} \\"
            ),
            (6,),
        ),
    )
    lines = [
        "% AUTO-GENERATED by pipeline render-paper1-tables -- do not edit by hand.",
        r"\begin{table}[H]",
        r"\centering",
        r"\small",
        r"\begin{tabularx}{\linewidth}{r>{\raggedright\arraybackslash}Xrrrrrr}",
        r"\toprule",
        (
            r"Spec. & Adjustment & $\hat\beta_{W_2}$ & $\Delta D$/1 SD & 95\% CI & "
            r"$p$ & $R^2_{\mathrm{full}}$ & $R^2_{\mathrm{partial}}$ \\"
        ),
        r"\midrule",
    ]
    for panel_index, (heading, spec_indices) in enumerate(panels):
        if panel_index:
            lines.append(r"\midrule")
        lines.append(heading)
        for spec_index in spec_indices:
            row = rows_by_spec[spec_index]
            adjustment = (
                r"+ within-firm dispersion ($B_i+B_j$, $|B_i-B_j|$)"
                if spec_index == _DISPERSION_SPEC_INDEX
                else _escape(
                    _DYADIC_ADJUSTMENT_LABELS.get(spec_index, str(row["label"]))
                )
            )
            ci = (
                f"[{_fmt(row.get('ci_low_w2_distance'), 3)}, "
                f"{_fmt(row.get('ci_high_w2_distance'), 3)}]"
            )
            lines.append(
                " & ".join(
                    [
                        str(spec_index),
                        adjustment,
                        _fmt(row.get("coef_w2_distance"), 3),
                        _fmt(row.get("effect_one_sd_w2_distance"), 3),
                        ci,
                        _fmt(row.get("pvalue_w2_distance"), 3),
                        _fmt(row.get("overall_r2"), 3),
                        # Conditional fit exists only where a restricted
                        # fixed-effect model does; pooled rungs carry None and
                        # render as an em dash rather than inviting a
                        # pooled-versus-FE comparison.
                        _fmt(row.get("within_r2"), 3),
                    ]
                )
                + r" \\"
            )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabularx}",
            (
                r"\caption{Dyadic association ladder. Every interval and two-sided "
                r"sign-tail probability uses the same deterministic multinomial "
                r"node-count array across rungs. Panel A separates the W2 "
                r"metric's staged pooled adjustments from canonical "
                r"specification 6, which absorbs symmetric additive firm effects. "
                r"Specification 5 conditions on the within-firm dispersion "
                r"components of article geometry and is a decomposition "
                r"diagnostic. "
                r"$\Delta D$/1 SD "
                r"is the fitted change in return chord distance for a one-standard-"
                r"deviation change in rooted W2 distance. "
                r"$R^2_{\mathrm{full}}$ is the full-model coefficient of "
                r"determination; the pooled and fixed-effect blocks absorb different "
                r"variation and are compared within block. "
                r"$R^2_{\mathrm{partial}} = 1 - "
                r"\mathrm{SSE}_{\mathrm{FE}+W_2}/\mathrm{SSE}_{\mathrm{FE}}$ is the "
                r"conditional fit against the restricted firm-effect model and is "
                r"undefined (\textemdash) for the pooled rungs, which have no such "
                r"restricted model.}"
            ),
            r"\label{tab:dyadic-ladder}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def _validated_primary_spec(
    summary: dict[str, object],
) -> tuple[int, dict[str, object]]:
    """Validate and return the governed primary W2 specification."""
    primary_spec_index = summary["primary_spec_index"]
    if isinstance(primary_spec_index, bool) or not isinstance(primary_spec_index, int):
        message = "dyadic summary primary_spec_index must be an integer"
        raise TypeError(message)
    model_ladder = summary["model_ladder"]
    if not isinstance(model_ladder, list):
        message = "dyadic summary model_ladder must be a list"
        raise TypeError(message)
    primary = next(
        (
            row
            for row in model_ladder
            if isinstance(row, dict)
            and int(row.get("spec_index", -1)) == primary_spec_index
        ),
        None,
    )
    if primary is None:
        message = f"primary W2 specification {primary_spec_index} is absent"
        raise ValueError(message)
    if primary.get("firm_effects") is not True:
        message = "primary W2 specification must use symmetric firm effects"
        raise ValueError(message)
    if primary.get("regressors") != ["w2_distance"]:
        message = "primary W2 specification has unexpected regressors"
        raise ValueError(message)
    if summary.get("se_type") != "multinomial node bootstrap (dyad weight w_i*w_j)":
        message = "dyadic design table requires multinomial node-bootstrap inference"
        raise ValueError(message)
    if summary.get("w2_scale") != "rooted balanced quadratic Wasserstein distance":
        message = "dyadic design table requires the governed rooted W2 input"
        raise ValueError(message)
    return primary_spec_index, primary
