"""DISCO table renderer."""

from __future__ import annotations

from typing import cast

from pipeline.figures.paper1._tables.format import _escape, _fmt, _fmt_int


def _render_disco_table(summary: dict[str, object]) -> str:
    location_values = [
        _fmt(summary.get("s_within"), 3),
        _fmt(summary.get("s_between"), 3),
        _fmt(summary.get("total_dispersion"), 3),
        _fmt(summary.get("r2_e"), 3),
        _fmt(summary.get("f_statistic"), 3),
        _fmt(summary.get("disco_perm_p"), 4),
    ]
    dispersion_values = [
        _fmt(summary.get("dispersion_f_statistic"), 3),
        _fmt(summary.get("dispersion_perm_p"), 3),
    ]
    sector_sizes = cast("dict[str, object]", summary.get("sector_sizes", {}))
    sector_text = ", ".join(
        f"{_escape(name)}={_fmt_int(count)}"
        for name, count in sorted(sector_sizes.items())
    )
    caption = (
        r"\caption{DISCO diagnostics on the canonical energy metric using the "
        r"cited V-statistic denominators. Panel A decomposes total dispersion "
        r"and tests sector-location structure. Panel B tests whether sector "
        r"dispersions differ; it is a diagnostic companion rather than a "
        r"second location test. Both tests use "
        + _fmt_int(summary.get("n_permutations"))
        + r" sector-label permutations over the fixed firm universe. The "
        r"principal-coordinate representation has "
        + _fmt_int(summary.get("pcoa_n_positive_axes"))
        + r" positive axes and minimum eigenvalue \num{"
        + f"{float(str(summary.get('pcoa_min_eigenvalue', 0.0))):.2e}"
        + r"}. Sector sizes are "
        + sector_text
        + r".}"
    )
    return "\n".join(
        [
            "% AUTO-GENERATED by pipeline render-paper1-tables -- do not edit by hand.",
            r"\begin{table}[H]",
            r"\centering",
            r"\small",
            r"\textit{Panel A: DISCO decomposition and location}",
            r"\par\smallskip",
            r"\begin{tabular}{rrrrrr}",
            r"\toprule",
            r"$S_W$ & $S_B$ & $T$ & $R_E^2$ & $F$ & $p_{\rm perm}$ \\",
            r"\midrule",
            " & ".join(location_values) + r" \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"\par\medskip",
            r"\textit{Panel B: dispersion diagnostic}",
            r"\par\smallskip",
            r"\begin{tabular}{rr}",
            r"\toprule",
            r"$F_{\rm disp}$ & $p_{\rm disp}$ \\",
            r"\midrule",
            " & ".join(dispersion_values) + r" \\",
            r"\bottomrule",
            r"\end{tabular}",
            caption,
            r"\label{tab:disco-decomposition}",
            r"\end{table}",
            "",
        ]
    )
