"""LaTeX table for the fixed-W2 random-exposure diagnostic."""

from __future__ import annotations

from typing import cast

from pipeline.figures.paper1._tables.format import _EM_DASH, _fmt


def _interval(row: dict[str, object], name: str) -> str:
    """Format an observed share with its node-bootstrap percentile interval."""
    return (
        f"{_fmt(row.get(f'{name}_share'), 3)} "
        f"[{_fmt(row.get(f'{name}_ci_low'), 3)}, "
        f"{_fmt(row.get(f'{name}_ci_high'), 3)}]"
    )


def _render_random_exposure_diagnostic(summary: dict[str, object]) -> str:
    """Render the maintained-scale W2 envelope scenarios."""
    n_dyads = summary.get("n_dyads")
    if isinstance(n_dyads, bool) or not isinstance(n_dyads, int) or n_dyads < 1:
        message = "random-exposure summary must declare a positive integer n_dyads"
        raise ValueError(message)
    diagnostic = cast(
        "dict[str, object]", summary.get("random_exposure_diagnostic", {})
    )
    scenarios = cast("list[dict[str, object]]", diagnostic.get("scenarios", []))
    lines = [
        "% AUTO-GENERATED by pipeline render-paper1-tables -- do not edit by hand.",
        r"\begin{table}[H]",
        r"\centering",
        r"\small",
        r"\begin{tabularx}{\linewidth}{rr>{\raggedleft\arraybackslash}X>{\raggedleft\arraybackslash}X>{\raggedleft\arraybackslash}X}",
        r"\toprule",
        r"$L$ & $\tau_i=\tau_j$ & Robust coverage & Unresolved & Robust violation \\",
        r"\midrule",
    ]
    if diagnostic.get("status") != "computed" or not scenarios:
        lines.append(r"\multicolumn{5}{c}{Unavailable: " + _EM_DASH + r"} \\")
    else:
        lines.extend(
            " & ".join(
                [
                    _fmt(row.get("L"), 2),
                    _fmt(row.get("tau"), 2),
                    _interval(row, "coverage"),
                    _interval(row, "unresolved"),
                    _interval(row, "violation"),
                ]
            )
            + r" \\"
            for row in scenarios
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabularx}",
            (
                r"\caption{Reduced-form fixed-W2 covariance-envelope diagnostic. "
                r"The article-embedding W2 is the exact balanced empirical "
                r"transport distance between 128-article measures under the "
                r"unit-chord ground cost. "
                r"Return moments are standardized total-return moments, so "
                r"$c^{\mathrm{actual}}_{ij}=2-2\rho_{ij}$. A dyad is covered "
                r"when the lower endpoint of the transport-excess interval is "
                r"nonnegative, violated when its upper endpoint is negative, "
                rf"and unresolved otherwise. Entries are shares of the {n_dyads:,} "
                r"dyads; brackets are percentile intervals from the common "
                r"multinomial node bootstrap. $L$ and $\tau$ are maintained "
                r"scales, not estimated from returns; the classifications are "
                r"not structural systematic-covariance estimates.}"
            ),
            r"\label{tab:random-exposure-w2}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


__all__ = ["_render_random_exposure_diagnostic"]
