# firecrawl/pdf-inspector — classifies a PDF as text-based or scanned without
# running OCR, and extracts position-aware text or Markdown. Not in nixpkgs.
# The classifier is the piece the documents group lacked: it decides whether
# OCRmyPDF/Tesseract are needed at all, instead of inferring it from empty
# `pdftotext` output.
#
# VENDORED LOCKFILE: upstream gitignores Cargo.lock ("optional for libraries"),
#   so there is nothing in-tree to pin resolution against and a bare `cargoHash`
#   would silently rot every time a transitive dependency published a compatible
#   version. ./pdf-inspector-Cargo.lock is generated by us and committed. It is
#   OURS to maintain: regenerate it whenever `rev` moves.
#
# BCMAPS: `find_bcmaps_dir()` falls back to `CARGO_MANIFEST_DIR/external/bcmaps`,
#   a build-time path that does not survive into the runtime closure — CID-font
#   ToUnicode extraction would degrade silently. Upstream offers a
#   `PDF_INSPECTOR_BCMAPS_DIR` override, so the maps are installed as real data
#   and the binaries are wrapped to point at them. `--set-default` so a caller
#   can still override. (The wasm build embeds them via `include_dir!`; native
#   builds do not.)
#
# BUMPING: update `rev` + `hash`, then regenerate the lockfile against the new
#   source — `cargo generate-lockfile` in an unpacked checkout — and commit both.
{
  fetchFromGitHub,
  makeWrapper,
  rustPlatform,
}:
rustPlatform.buildRustPackage {
  pname = "pdf-inspector";
  version = "0.1.7-unstable-2026-08-06";
  src = fetchFromGitHub {
    owner = "firecrawl";
    repo = "pdf-inspector";
    rev = "f731e1191ca8c3adeda4a12be44a6c5cae0ab807";
    hash = "sha256-jyKo3/j2xXcYMGS2ajDfqBi6kSy6/QXaOa/S9q/V4R0=";
  };
  cargoLock.lockFile = ./pdf-inspector-Cargo.lock;
  postPatch = ''
    cp ${./pdf-inspector-Cargo.lock} Cargo.lock
  '';

  nativeBuildInputs = [ makeWrapper ];

  postInstall = ''
    mkdir -p $out/share/pdf-inspector
    cp -r external/bcmaps $out/share/pdf-inspector/bcmaps
    for bin in $out/bin/*; do
      wrapProgram "$bin" \
        --set-default PDF_INSPECTOR_BCMAPS_DIR $out/share/pdf-inspector/bcmaps
    done
  '';

  meta.mainProgram = "pdf2md";
}
