"""Headline return-panel, configuration, and corpus bindings."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pipeline.io.values import Blank, Comment, PublicationValue

if TYPE_CHECKING:
    from pipeline.io.values import Record


def _initial_paper1_records(
    return_panel: dict[str, Any] | None,
    oos_return_panel: dict[str, Any] | None,
) -> list[Record]:
    records: list[Record] = [
        Comment(
            "AUTO-GENERATED by pipeline render-paper1-numbers — do not edit by hand."
        ),
    ]
    if return_panel:
        records += [
            Blank(),
            Comment(
                "--- Exact complete-case return panel "
                "(data/shared/covariance_matrix.parquet metadata) ---"
            ),
            PublicationValue(
                "return-panel-n-observations",
                int(return_panel["return_panel_rows"]),
            ),
            PublicationValue(
                "return-panel-n-tickers", int(return_panel["return_panel_columns"])
            ),
            PublicationValue(
                "return-panel-date-start", str(return_panel["return_panel_start_date"])
            ),
            PublicationValue(
                "return-panel-date-end", str(return_panel["return_panel_end_date"])
            ),
        ]
    if oos_return_panel:
        records += [
            Blank(),
            Comment(
                "--- Timing-separated complete-case return panel "
                "(data/shared/oos/covariance_matrix.parquet metadata) ---"
            ),
            PublicationValue(
                "oos-return-panel-n-observations",
                int(oos_return_panel["return_panel_rows"]),
            ),
            PublicationValue(
                "oos-return-panel-n-tickers",
                int(oos_return_panel["return_panel_columns"]),
            ),
            PublicationValue(
                "oos-return-panel-date-start",
                str(oos_return_panel["return_panel_start_date"]),
            ),
            PublicationValue(
                "oos-return-panel-date-end",
                str(oos_return_panel["return_panel_end_date"]),
            ),
        ]
    return records


def _append_configuration_records(
    records: list[Record],
    params: dict[str, Any] | None,
    model: str,
) -> None:
    if params:
        symbols = params.get("symbols", []) or []
        matryoshka_range = params.get("matryoshka_range", []) or []
        embed_cfg = params.get("embedding", {}).get("models", {}).get(model, {}) or {}
        start_year = str(params.get("start_date", ""))[:4]
        end_year = str(params.get("end_date", ""))[:4]
        records += [
            Blank(),
            Comment("--- Pipeline configuration (params.yaml) ---"),
            PublicationValue("n-samples-cap", int(params.get("n_samples", 0))),
            PublicationValue(
                "annual-raw-article-floor",
                int(params.get("annual_raw_article_floor", 0)),
            ),
            PublicationValue("n-firms-news", len(symbols)),
            PublicationValue(
                "matryoshka-dim-low",
                int(matryoshka_range[0])
                if len(matryoshka_range) > 0 and matryoshka_range[0] is not None
                else 0,
            ),
            PublicationValue(
                "matryoshka-dim-mid",
                int(matryoshka_range[1])
                if len(matryoshka_range) > 1 and matryoshka_range[1] is not None
                else 0,
            ),
            PublicationValue("embed-dim", int(embed_cfg.get("dims", 0))),
            PublicationValue("sample-year-start", int(start_year)),
            PublicationValue("sample-year-end", int(end_year)),
        ]


def _append_corpus_records(
    records: list[Record],
    corpus_summary: dict[str, Any] | None,
    params: dict[str, Any] | None,
) -> None:
    if corpus_summary:
        rows_in = int(corpus_summary.get("rows_in", 0))
        rows_out = int(corpus_summary.get("rows_out", 0))
        duplicates_dropped = int(corpus_summary.get("duplicates_dropped", 0))
        date_min = str(corpus_summary.get("date_min", ""))[:4]
        date_max = str(corpus_summary.get("date_max", ""))[:4]
        hist = corpus_summary.get("per_year_histogram", {}) or {}
        start_y = int(str(params.get("start_date", ""))[:4]) if params else 2018
        end_y = int(str(params.get("end_date", ""))[:4]) if params else 2022
        window_total = sum(
            int(v) for k, v in hist.items() if start_y <= int(k) <= end_y
        )
        records += [
            Blank(),
            Comment("--- News corpus summary (data/shared/corpus/summary.yaml) ---"),
            PublicationValue("corpus-raw-records", rows_in),
            PublicationValue("corpus-articles-total", rows_out),
            PublicationValue("corpus-duplicates-dropped", duplicates_dropped),
            PublicationValue("corpus-year-min", int(date_min)),
            PublicationValue("corpus-year-max", int(date_max)),
            PublicationValue("corpus-articles-window", window_total),
        ]
